Restrictions:
  max-price: 1000
  min-price: 1
Region: # players can only do /ah within these limits
  x-max: 20
  x-min: 10
  z-max: 20
  z-min: 10
Messages:
  prefix: '[&c&lCloakAuctions&r] &7'
  price-restriction-error: '&cThe price must be between %min-price% and %max-price%.'
  invalid-price: '&cThat is an invalid price.'
  no-item-in-hand: '&cYou must have an item in your hand.' # sent if player tries to sell air
  item-sold: '%prefix%Your item has been sold for &a$%price%&c.'
  not-at-spawn: '&cYou must be at spawn to do this!'